# Generated by Django 3.0.5 on 2020-04-22 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='offer price')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='delivery days')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='end datetime')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.ManyToManyField(blank=True, to='product.ProductColor')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('size', models.ManyToManyField(blank=True, to='product.ProductSize')),
            ],
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
