# Generated by Django 3.0.5 on 2020-04-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200423_0954'),
        ('product', '0003_auto_20200423_1128'),
    ]

    operations = [
    ]
