# Generated by Django 3.0.4 on 2020-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
