# Generated by Django 3.0.5 on 2020-04-22 10:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, verbose_name='phone'),
        ),
    ]
