# Generated by Django 3.0.4 on 2020-04-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200414_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='postcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.Postcode'),
        ),
    ]
