# Generated by Django 3.0.4 on 2020-04-27 11:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200422_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, unique=True, verbose_name='phone'),
        ),
    ]
