# Generated by Django 3.0.5 on 2020-05-01 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200427_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cvr_number',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)], verbose_name='CVR number'),
        ),
    ]
