# Generated by Django 3.0.5 on 2020-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_cvr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='order_delivery',
            field=models.BooleanField(default=False, verbose_name='offer customer delivery'),
        ),
        migrations.AddField(
            model_name='shop',
            name='order_pickup',
            field=models.BooleanField(default=True, verbose_name='offer customer pickup'),
        ),
    ]
