# Generated by Django 3.0.4 on 2020-04-16 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
