# Generated by Django 3.0.5 on 2020-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200501_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='order_delivery',
            field=models.BooleanField(default=False, verbose_name='offers order delivery'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='order_pickup',
            field=models.BooleanField(default=True, verbose_name='offers order pickup'),
        ),
    ]
