# Generated by Django 3.0.5 on 2020-05-01 11:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200501_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_image',
            field=stdimage.models.JPEGField(default='images/2020/04/16/image.png', upload_to='images/shop/%Y/%m/%d/', verbose_name='shop_image'),
        ),
    ]
