# Generated by Django 3.0.5 on 2020-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='order_delivery',
            field=models.BooleanField(default=False, verbose_name='offer order delivery'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='order_pickup',
            field=models.BooleanField(default=True, verbose_name='offer order pick-up at shop'),
        ),
    ]
