# Generated by Django 3.0.5 on 2020-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200504_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_range',
            field=models.IntegerField(choices=[(-1, 'No delivery'), (5, '5KM from shop'), (10, '10KM from shop')], default=-1, verbose_name='Delivery range'),
        ),
    ]
