# Generated by Django 3.0.5 on 2020-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shop_delivery_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='order_delivery',
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_range',
            field=models.IntegerField(choices=[(-1, 'Do Not offer delivery'), (5, '5KM from shop'), (10, '10KM from shop')], default=-1, verbose_name='Delivery range'),
        ),
    ]
