# Generated by Django 3.0.6 on 2020-05-18 08:04

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200504_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=stdimage.models.JPEGField(blank=True, null=True, upload_to='images/shop/%Y/%m/%d/', verbose_name='shop_image'),
        ),
    ]
