# Generated by Django 3.0.4 on 2020-05-18 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200504_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cvr_number',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)], verbose_name='CVR number'),
        ),
    ]
