# Generated by Django 3.0.4 on 2020-05-18 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200518_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cvr_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)], verbose_name='CVR number'),
        ),
    ]
