# Generated by Django 3.0.6 on 2020-05-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200518_0715'),
        ('shop', '0012_auto_20200518_1239'),
    ]

    operations = [
    ]
