# Generated by Django 3.0.4 on 2020-04-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('alten_admin', 'Can administrate shops in Alten Admin'),)},
        ),
    ]
