# Generated by Django 3.0.4 on 2020-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Bestilt'), (2, 'Accepteret'), (3, 'Afsendt'), (4, 'Afvist')], default=1),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
