# Generated by Django 3.0.4 on 2020-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add price field to orderItem model
    """
    dependencies = [
        ('order', '0002_auto_20200331_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=(0.00), max_digits=10),
            preserve_default=False,
        ),
    ]
